kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:1.22
    commands:
      - go test

  - name: build
    image: golang:1.22
    commands:
      - go build -o myapp .

  - name: run
    image: golang:1.22

trigger:
  event:
    - push
  branch:
    - main

---

kind: pipeline
type: exec
name: deploy

steps:
  - name: deploy
    commands:
      - ./myapp
    detach: true

trigger:
  event:
    - push
  branch:
    - main
