kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:1.22
    commands:
      - go test

  - name: build
    image: golang:1.22
    commands:
      - go build -o app .

  - name: publish
    image: plugins/docker
    settings:
      repo: jadev118/cerebral
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: ./dockerfile   # Specify the Dockerfile path if it's not in the default location
      context: .
  
  - name: deploy
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stop cerebral || true
      - docker rm cerebral || true
      - docker pull jadev118/cerebral:latest
      - docker run -d --name cerebral --rm -p 8080:8080 jadev118/cerebral:latest

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push
    - pull_request

