kind: pipeline
type: exec
name: default

steps:
  - name: test
    commands:
      - go test

  - name: build
    commands:
      - go build -o myapp .

  - name: run
    commands:
      - ./myapp
    detach: true
trigger:
  event:
    - push
  branch:
    - main

