kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:1.22
    commands:
      - go test

  - name: build
    image: golang:1.22
    commands:
      - go build -o myapp .

  - name: run
    image: golang:1.22
    commands:
      - ./myapp
    ports:
      - 8080
    detach: true

trigger:
  event:
    - push
  branch:
    - main

