[[services]]
  name = "trueNAS"
  url = "http://10.0.0.20"

[[services]]
  name = "Proxmox"
  url = "https://10.0.0.158:8006"

[[services]]
  name = "Jellyfin"
  url = "http://10.0.0.163:8096"

[[services]]
  name = "qBittorrent"
  url = "http://10.0.0.66:8090/"

[[services]]
  name = "Portainer"
  url = "https://10.0.0.172:9443/#!/init/admin"
